version: '3.8'


    #volumes:
    #  postgres-data: var/lib/postgresql/data
x-shared:
  &common
  NEO4J_AUTH: neo4j/j4neo
  NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"

services:
  neo4j:
    image: neo4j:4.2.5-enterprise
    network_mode: "bridge"
    restart: unless-stopped
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_memory_pagecache_size=512m
      - NEO4J_dbms.memory.heap.initial_size=512m
      - NEO4J_dbms_memory_heap_max__size=512m
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      #- NEO4J_dbms.allow_format_migrations=true # 7 db in 7 weeks.
      #- NEO4J_dbms_active__database=movies.db # 7 in 7
      - NEO4JLABS_PLUGINS=["graph-data-science"]
    volumes:
      - ./volume/conf:/var/lib/neo4j/conf
      - ./volume/plugins:/plugins
      - ./volume/data:/data
      - ./volume/import:/import
      - ./volume/logs:/logs
  postgresql:
    image: "postgres:13.3-alpine"
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: examDB
      PGDATA: var/lib/postgresql/data
    #volumes:
    #  postgres-data: var/lib/postgresql/data
  redis:
        image: redis:alpine
        ports:
            - 6379:6379
        volumes:
            - ./config/redis.conf:/redis.conf
        command: [ "redis-server", "/redis.conf" ]


  