version: '3.8'

services:
  postgresql:
    image: "postgres:13.3-alpine"
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: examDB
      PGDATA: var/lib/postgresql/data
    volumes:
      - postgres-data:var/lib/postgresql/data
  jupyter:
    build: ./jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter:/app
    entrypoint:
      jupyter lab --ip='0.0.0.0' --port=8888 --no-browser --allow-root
volumes:
      - postgres-data: